# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'
        cache-dependency-path: go.sum

    - name: Test
      run: go test -v ./...